[ec2]
redirect-server ansible_host=52.3.35.1

[ec2:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/redirect-sandbox-key.pem
ansible_python_interpreter=/usr/bin/python3

# Django environment
django_secret_key=sandbox-secret-key-change-in-production-4829
django_debug=False
django_allowed_hosts=52.3.35.1
db_host=redirect-core-postgresdb113281d2-lhzna00epldw.cgbo4w6c0n8s.us-east-1.rds.amazonaws.com
db_name=redirectdb
db_user=dbadmin
db_password=m=e8-RXLZkSRZGk.7E8GbpVy=ZiFp9
db_port=5432
github_repo=https://github.com/balalaika-coder/redirect-sandbox_v4.0.git
api_gateway_url=https://03q5gzc3qb.execute-api.us-east-1.amazonaws.com/prod/
webhook_secret=sandbox-webhook-secret-2024

