# Generated by Django 6.0.4 on 2026-04-24 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='e.g., trendaisecurity.com', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g., trendai', max_length=100, unique=True)),
                ('webhook_url', models.URLField(blank=True, help_text='API Gateway webhook URL for sync')),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret for webhook auth', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('geo_locale_map', models.JSONField(blank=True, default=dict, help_text='Map of country codes to locale paths, e.g., {"US": "/en-us", "DE": "/de"}')),
                ('geo_default_locale', models.CharField(blank=True, help_text='Default locale path for unrecognized countries, e.g., /en-us', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('import', 'Bulk Import')], max_length=20)),
                ('entity_type', models.CharField(help_text='e.g., Redirect, Site', max_length=50)),
                ('entity_id', models.IntegerField()),
                ('diff', models.JSONField(blank=True, help_text='JSON object showing what changed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='redirects_d_entity__2c3467_idx'), models.Index(fields=['user_email'], name='redirects_d_user_em_926793_idx'), models.Index(fields=['-created_at'], name='redirects_d_created_2ab507_idx')],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source path, e.g., /old-page', max_length=2048)),
                ('destination', models.CharField(help_text='Destination URL or path', max_length=2048)),
                ('status_code', models.IntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary'), (307, '307 Temporary (Preserve Method)')], default=301)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('regex', 'Regular Expression'), ('vanity', 'Vanity URL')], default='exact', max_length=10)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = evaluated first (for regex)')),
                ('geo_aware', models.BooleanField(default=False, help_text='Enable geo-aware routing with locale overrides')),
                ('geo_locale_allowlist', models.JSONField(blank=True, help_text='List of allowed locales for phased rollout, e.g., ["de", "fr"]. Requires geo_aware=True.', null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Redirect becomes active at this time', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Redirect stops being active at this time', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Last time this redirect was published to CloudFront', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects_updated', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='redirects_django.site')),
            ],
            options={
                'ordering': ['-priority', 'source'],
            },
        ),
        migrations.CreateModel(
            name='UserSiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor')], default='editor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='redirects_django.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='RedirectLocaleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text='Locale path from site geo_locale_map, e.g., /de', max_length=50)),
                ('destination', models.CharField(help_text='Destination path for this locale, e.g., /de/produkte', max_length=2048)),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locale_overrides', to='redirects_django.redirect')),
            ],
            options={
                'ordering': ['locale'],
                'unique_together': {('redirect', 'locale')},
            },
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['site', 'is_active'], name='redirects_d_site_id_d28ece_idx'),
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['site', 'source'], name='redirects_d_site_id_34cd7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together={('site', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='usersiterole',
            unique_together={('user', 'site')},
        ),
    ]
